In [3]:
import numpy as np

In [4]:
ln = np.array([1,2,3,4,5,6])

In [5]:
ln = np.zeros((3,2))

In [6]:
ln = np.ones((3,3))

In [7]:
ln = np.arange(0,101,10)

In [8]:
#ln = np.where(ln%2==0) 

In [9]:
ln = np.linspace(0, 10, 12)

In [10]:
#for i in ln:
#   print(i*2)

In [11]:
ln = np.eye(4)

In [12]:
ln = np.array([[1,2,9],[2,5,7],[3,5,7],[9,1,3]])
print(ln.ravel())
print(ln.flatten())

[1 2 9 2 5 7 3 5 7 9 1 3]
[1 2 9 2 5 7 3 5 7 9 1 3]


In [13]:
ln = np.array([1,2,3])
an = np.array([3,4,5])
print(ln+1)
print(ln-1)
print(ln*2)
print(ln/4)
print(ln+an)

[2 3 4]
[0 1 2]
[2 4 6]
[0.25 0.5  0.75]
[4 6 8]


In [14]:
ln = np.array([0,0,3,0,5])
mask = ln > 3
print(mask)
print(ln[mask])

[False False False False  True]
[5]


In [15]:
print(ln[0,1])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed