In [128]:
import numpy as np

In [156]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [130]:
arr2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

In [131]:
print(np.max(arr1 + arr2))

10


In [132]:
print(arr1.ravel())

[1 2 3 4 5 6 7 8 9]


In [133]:
print(arr1.flatten())

[1 2 3 4 5 6 7 8 9]


In [134]:
print(np.all(arr1))

True


In [135]:
print(np.random.randn(5).round(2)*100)

[-48.  16.  23.  12. 146.]


In [136]:
print(np.random.permutation(arr1))

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [137]:
print(np.random.shuffle(arr1))

None


In [138]:
ln = np.array([5,3,4,1,2])
np.random.shuffle(ln)
print(ln)

[5 3 1 2 4]


In [139]:
print(np.random.choice(arr1.flatten(),size=5))

[6 1 7 3 6]


In [140]:
np.random.seed(42)

In [151]:
print(np.random.randint(0,10,size=1))

[3]


In [165]:
arr3 = np.array([1,2,3])
print(np.argmax(arr3))

2


In [168]:
print(np.indices(arr3))

[[[[0 0 0]
   [0 0 0]]]


 [[[0 0 0]
   [1 1 1]]]


 [[[0 1 2]
   [0 1 2]]]]


In [169]:
print(np.dot(arr1,arr2))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [170]:
print(arr1*arr2)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [178]:
A = np.array([[1, 2], [3, 4]])
print(round(np.linalg.det(A)))

-2
